---
    
  - name: backup hosts file
    shell: mv /etc/hosts /etc/hosts_bak

  - name: copy hosts file
    copy: 
      src: hosts 
      dest: /etc/ 
      owner: root 
      group: root 
      mode: 0644

  - name: stop and disable firewalld.
    service:
       name: firewalld
       state: stopped
       enabled: False

  - name: restart network service
    shell: systemctl restart network

  - name: disable selinux
    selinux: 
      state: disabled

