---

- name: groupadd es
  group: 
      name: "{{ elasticsearch_group }}"
      gid: "1000"

- name: useradd es
  user:
    name: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    createhome: yes

- name: mkdir for elasticsearch home
  file: 
    dest: "{{ elasticsearch_home }}"
    mode: 0755
    state: directory
    owner: "{{ elasticsearch_user }}" 
    group: "{{ elasticsearch_group }}"
    
- name: copy and unzip elasticsearch.tar.gz to hosts
  unarchive: 
      src: "{{ elasticsearch_tarball }}"
      dest: "{{ elasticsearch_install_path }}"


- name: modify elasticsearch configuration 
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
      - { src: 'elasticsearch.yml.j2', dest: '{{ elasticsearch_home }}/config/elasticsearch.yml' }
      - { src: 'jvm.options.j2', dest: '{{ elasticsearch_home }}/config/jvm.options' } 
  notify: 
      - restart elasticsearch
  tags: es_conf

- name: mkdir dir for logs data
  file: 
    dest: "{{ elasticsearch_home }}/logs"
    mode: 0755 
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"

- name: change owner and group
  file: 
    path: "{{ elasticsearch_home }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    recurse: yes

- name: make elasticsearch permission
  shell: su - {{ elasticsearch_user }}  -c 'chmod +x {{ elasticsearch_home }}/bin/*'

- name: start es
  remote_user: root
  shell: su - {{ elasticsearch_user }}  -c '{{ elasticsearch_home }}/bin/elasticsearch -d'
  tags:
    - start elasticsearch