---

- name: groupadd es
  group: 
      name: "{{ elasticsearch_group }}"
      gid: "9200"
  tags:
    - install

- name: useradd es
  user:
    name: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    createhome: yes
  tags:
    - install


- name: mkdir for elasticsearch home
  file: 
    dest: "{{ elasticsearch_home }}"
    mode: 0755
    state: directory
    owner: "{{ elasticsearch_user }}" 
    group: "{{ elasticsearch_group }}"
  tags:
    - install

    
- name: copy and unzip elasticsearch.tar.gz to hosts
  unarchive: 
      src: "{{ elasticsearch_tarball }}"
      dest: "{{ elasticsearch_install_path }}"
  tags:
    - install


- name: modify elasticsearch configuration 
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
      - { src: 'elasticsearch.yml.j2', dest: '{{ elasticsearch_home }}/config/elasticsearch.yml' }
      - { src: 'jvm.options.j2', dest: '{{ elasticsearch_home }}/config/jvm.options' } 
  tags: 
    - configure
    - install
   

- name: mkdir dir for logs data
  file: 
    dest: "{{ elasticsearch_home }}/logs"
    mode: 0755 
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
  tags:
    - install


- name: change owner and group
  file: 
    path: "{{ elasticsearch_home }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_group }}"
    recurse: yes
  tags:
    - install


- name: restart elasticsearch
  #  shell: su - {{ elasticsearch_user }}  -c 'chmod +x {{ elasticsearch_home }}/bin/*'
  shell: ls
  notify: 
    - restart elasticsearch
  tags: 
    - install
    - restart

- name: stop elasticsearch
  shell: ls
  notify: 
    - stop elasticsearch
  tags: 
    - stop

- name: start elasticsearch
  shell: ls
  notify: 
    - start elasticsearch
  tags: 
    - start



#- name: start es
#  remote_user: root
#  shell: su - {{ elasticsearch_user }}  -c '{{ elasticsearch_home }}/bin/elasticsearch -d'
#  tags:
#    - start elasticsearch