---

- name: set timezone to Asia/Shanghai
  shell: timedatectl set-timezone Asia/Shanghai
  tags: 
    - install

- name: mkdir for ntp home
  file: 
    dest: "{{ ntp_install_path }}"
    mode: 0755
    state: directory
    owner: "{{ ntp_user }}" 
    group: "{{ ntp_group }}"
  tags: 
    - install

- name: copy ntp rpms
  copy:
    src: "{{ item }}"
    dest: "{{ ntp_install_path }}"
    owner: root
    mode: 777
  with_fileglob:
    - files/*
  tags: 
    - install

- name: get all ntp rpms 
  find:
    paths: "{{ ntp_install_path }}"
    patterns: "*.rpm"
  register: ntp_rpms
  tags: 
    - install

- name: install ntp rpms
  yum:
    name: "{{ item.path }}"
    state: present
  with_items: "{{ ntp_rpms.files }}"
  tags: 
    - install

- name: modify ntp configuration 
  template: 
    src: "ntp.conf.server.j2"
    dest: "/etc/ntp.conf"
  when: ansible_hostname in groups['ntp-server']
  tags: 
    - install
    - configure

- name: modify ntp configuration 
  template: 
    src: "ntp.conf.client.j2"
    dest: "/etc/ntp.conf"
  when: ansible_hostname in groups['ntp-clients']
  tags: 
    - install
    - configure

- name: restart ntp service
  shell: 
    systemctl restart ntpd
  when: ansible_hostname in groups['ntp-server']
  tags: 
    - install
    - aysc

- name: clients synchronize time to server
  shell: ntpdate {{ hostvars[groups['ntp-server'][0]].ipv4_address|default(hostvars[groups['ntp-server'][0]]['ansible_default_ipv4']['address']) }}
  when: ansible_hostname in groups['ntp-clients']
  tags: 
    - install
    - aysc

- name: add cron task
  cron: 
    name: ntpdate 
    job: "/usr/sbin/ntpdate {{ hostvars[groups['ntp-server'][0]].ipv4_address|default(hostvars[groups['ntp-server'][0]]['ansible_default_ipv4']['address']) }} >> /tmp/ntpdate.log 2>&1"
    minute: "0"
    hour: "1"
  tags: 
    - install

