---

- name: mkdir for zookeeper home
  file: 
    dest: "{{ zookeeper_home }}"
    mode: 0755
    state: directory
    owner: "{{ zookeeper_user }}" 
    group: "{{ zookeeper_group }}"
  tags:
    - install

    
- name: copy and unzip zookeeper.tar.gz to hosts
  unarchive: 
      src: "{{ zookeeper_tarball }}"
      dest: "{{ zookeeper_install_path }}"
  tags:
    - install


- name: mkdir for zookeeper data 
  file: 
    dest: "{{ zookeeper_data_dir }}"
    mode: 0755
    state: directory
    owner: "{{ zookeeper_user }}" 
    group: "{{ zookeeper_group }}"
  tags:
    - install


- name: mkdir for zookeeper log 
  file: 
    dest: "{{ zookeeper_log_dir }}"
    mode: 0755
    state: directory
    owner: "{{ zookeeper_user }}" 
    group: "{{ zookeeper_group }}"
  tags:
    - install


- name: modify zookeeper configuration 
  template: 
    src: "zoo.cfg.j2"
    dest: "{{ zookeeper_home }}/conf/zoo.cfg"
  tags: 
    - install
    - configure

- name: modify zookeeper configuration 
  template: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'myid.j2', dest: '{{ zookeeper_data_dir }}/myid' }
    - { src: 'zoo.cfg.j2', dest: '{{ zookeeper_home }}/conf/zoo.cfg' }
    - { src: 'zkEnv.sh.j2', dest: '{{ zookeeper_home }}/bin/zkEnv.sh' }
  tags: 
    - install
    - configure

- name: change owner and group
  file: 
    path: "{{ zookeeper_home }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    recurse: yes
  tags:
    - install


- name: stop zookeeper
  shell: sh {{ zookeeper_home }}/bin/zkServer.sh stop
  become: true
  become_method: su
  become_user: root
  tags:
    - stop 
    - restart
    - install

- name: start zookeeper
  shell: sh {{ zookeeper_home }}/bin/zkServer.sh start
  become: true
  become_method: su
  become_user: root
  tags:
    - start 
    - restart
    - install